### ISSUE TITLE
Inconsistent configuration naming

### ISSUE THREAD

**Issue by jdecool** [novaway/NovawayFileManagementBundle#45]
The bundle define 2 configuration options for the same thing.

In the `DependencyInjection/Configuration.php` :
```yaml
novaway_file_management:
    web_file_path: ~
```

`Resources/config/services.yml` file use `novaway.fmb.webdir` :
```yaml
# [...]
services:
    # [...]
    novaway.fmb.form.type.image:
        class: %novaway.fmb.form.type.image.class%
        arguments: [%novaway.fmb.webdir%]
        tags:
            - { name: form.type, alias: image }
```
